name: Assemble
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
         ref: 'releases'
         path: 'release'
      - uses: actions/setup-node@v2
      - run: npm install clean-css uglify-js
      - run: make
      - uses: EndBug/add-and-commit@v7
        with:
          branch: 'releases'
          cwd: 'release'
          add: 'lsfont.html'
